### PR TITLE
clustergrammer tool 

### PR DESCRIPTION
**Pull request by emily101-gif**
Also added galaxy1 version

### CODE REVIEW

**Comment by emily101-gif** [comment]
Error when running this tool: 
- jinja is in the requirements tools so confused by this error 
Traceback (most recent call last):
File "/home/combee/galaxy/immport-galaxy-tools/flowtools/clustergrammer_flow/clustergrammerIPG.py", line 19, in <module>
from jinja2 import Environment, FileSystemLoader
ModuleNotFoundError: No module named 'jinja

**Comment by pcm32** [comment]
Currently failing because clustergrammer is using pandas constructs that have been long deprecated and now removed. Either we pin back to an old version of clustergrammer or do a PR with changes to that repo.

```
  File "/Users/pmoreno/miniconda3/envs/mulled-v1-fce1fd9acabd1ba0a088f9eb3f5944467f7d63c11968a86a613806b675670142/lib/python3.8/site-packages/clustergrammer/run_filter.py", line 74, in grab_df_subset
    df = df.ix[keep_rows]
  File "/Users/pmoreno/miniconda3/envs/mulled-v1-fce1fd9acabd1ba0a088f9eb3f5944467f7d63c11968a86a613806b675670142/lib/python3.8/site-packages/pandas/core/generic.py", line 5274, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'ix'
```

**Comment by pcm32** [comment]
TODO: We also need to add some js to the tool folder, on consume this from online repos.

**Review by pcm32 — APPROVED** [review]
LGTM, checked against files in immport-galaxy repo, nothing newer there.

**Pull request merged**
