### PR TITLE
Flowclr sample name

### PR DESCRIPTION
**Pull request by pcm32**
This PR replaces #96

### CODE REVIEW

**Comment by emily101-gif** [comment]
Hi @pcm32 made a few changes to the help file. Also in the help section about the input files. It says there is an option to abbreviate the file names prior to fullstop, but I can't see a way to do this. Are you ok with me removing this part? Also for some reason the output data appears tabular in the help file but the input example does not. I've tried viewing it in an XML viewer and it all looks fine so it would be great if you could take a look at this. Thanks.

**Comment by pcm32** [comment]
>  It says there is an option to abbreviate the file names prior to fullstop, but I can't see a way to do this. Are you ok with me removing this part?

@emily101-gif  I didn't notice that that functionality was promised in the help, but we can add it if you want it (or remove the help entry as you suggest, if you feel that this is not crucial). 

> Also for some reason the output data appears tabular in the help file but the input example does not. 

I'm sorry, I'm not getting exactly what you mean here, is this the part I'm supposed to ignore based on what you said in teams?

**Comment by pcm32** [comment]
This looks good to me for merging @emily101-gif, once your concerns above are satisfied. Let me know!

**Comment by emily101-gif** [comment]
Hi Pablo. For now I have removed the part of the help file which was no longer relevant to the tool. The only issue is that in the help section the example input files are still not appearing in a tabular format. I have attached a picture so you can see. 
Apart from that I am also happy with this tool. Thanks again :) 

Annotation 2020-07-23 103532

**Comment by pcm32** [comment]
Ok, thanks for the clarification, I didn't understand before that it was the help that you were referring to.

**Comment by pcm32** [comment]
This should now fix it.

**Comment by pcm32** [comment]
Will merge this given that we have fixed the help formatting.

**Pull request merged**
