### PR TITLE
auto_collapse_pops tool

### PR DESCRIPTION
**Pull request by emily101-gif**
from ig- repo

### CODE REVIEW

**Comment by pcm32** [comment]
Ohhh, gosh, sorry, I made a mistake here... could you please push again your local branch emily101-gif-patch here?

**Comment by pcm32** [comment]
(and reopen)

**Comment by pcm32** [comment]
(ok, fixed now!)

**Comment by emily101-gif** [comment]
> (and reopen)
Thanks for fixing.

**Review by pcm32 — APPROVED** [review]

**Pull request merged**
