### PR TITLE
FlowSOMgeneratetree tool

### PR DESCRIPTION
**Pull request by emily101-gif**
Add R script to tool
Minor change to help section in XML file

### CODE REVIEW

**Review by pcm32 — APPROVED** [review]
LGTM

**Comment by emily101-gif** [comment]
@pcm32 I believe this tool is ready to go as well - so added the label.

**Comment by pcm32** [comment]
@emily101-gif could you please check what user is the .shed file using and whether this is already present at the Galaxy toolshed? if it is present, then user should be immport-devteam, otherwise azomics.

**Comment by emily101-gif** [comment]
> @emily101-gif could you please check what user is the .shed file using and whether this is already present at the Galaxy toolshed? if it is present, then user should be immport-devteam, otherwise azomics.

Hi Pablo. This tool isn't in the tool shed so can stay as azomics user group. Thank you again for all your help with the tools.  @pcm32

**Pull request merged**
