### PR TITLE
runCrossSample tool

### PR DESCRIPTION
**Pull request by emily101-gif**

### CODE REVIEW

**Comment by pcm32** [comment]
@emily101-gif I have fixed the galaxy issues of the tool, but the tests are currently not passing because the flowstat3 test files are not equivalent to what the tool is outputting. Currently output1.flowstat3 and output2.flowstat3 files have around 16 more lines than the outputs generated by the tools:

```
JobOutputsError: History item  different than expected, difference (using diff):
( /var/folders/23/wwh84vd95rncnf5mx753cpgh0000gp/T/tmp8VmHXbout1.flowstat3 v. /var/folders/23/wwh84vd95rncnf5mx753cpgh0000gp/T/tmpO7Fkyxout1.flowstat3 )
--- local_file
+++ history_data
@@ -1,27 +1,27 @@
 Population	FSC_mean	FSC_median	FSC_stdev	SSC_mean	SSC_median	SSC_stdev	CD4_mean	CD4_median	CD4_stdev	CCR7_mean	CCR7_median	CCR7_stdev	CD8_mean	CD8_median	CD8_stdev	CCR3_mean	CCR3_median	CCR3_stdev	Percentage_mean	Percentage_median	Percentage_stdev
-1	362.36	362.36	2.03	115.66	115.66	4.69	520.22	520.22	2.1	187.01	187.01	8.0	49.3	49.3	1.43	71.62	71.62	6.22	9.53	9.53	0.92
-2	434.28	374.35	111.03	173.06	125.62	92.77	481.01	521.93	74.19	53.87	39.72	27.49	123.6	72.0	94.92	262.34	197.55	140.75	4.77	5.35	4.11
-3	387.79	395.7	23.62	130.91	119.3	27.93	435.9	410.23	67.59	74.72	69.3	9.68	600.1	585.6	29.27	329.66	275.2	135.27	3.65	0.15	6.14
-4	362.46	363.32	6.82	204.27	204.11	37.15	89.98	96.34	14.26	176.99	147.5	52.47	99.4	102.85	11.5	379.43	318.19	129.33	2.15	0.42	3.06
-5	325.38	320.36	10.17	160.67	155.29	19.56	59.04	56.73	12.13	89.3	81.95	21.59	86.04	73.35	29.85	138.09	112.25	52.08	3.85	4.61	3.27
-6	368.28	368.59	11.22	150.66	148.89	19.84	72.55	69.32	5.76	104.15	96.05	37.15	610.48	612.42	3.86	266.97	244.06	45.55	6.11	3.08	6.26
-7	396.63	403.26	20.5	168.46	176.59	16.14	87.66	94.51	12.08	279.23	281.53	86.3	621.35	620.71	1.55	304.29	274.19	61.37	3.9	2.99	1.61
-8	404.55	404.55	47.31	144.35	144.35	45.71	517.41	517.41	0.11	341.18	341.18	115.72	460.13	460.13	258.52	471.42	471.42	48.2	5.63	5.63	7.93
-9	411.14	431.34	58.13	304.59	331.2	81.01	255.21	292.9	108.35	576.55	562.5	181.39	376.48	302.14	136.76	558.62	616.89	126.67	0.5	0.18	0.68
-10	355.5	355.5	4.74	112.88	112.88	3.84	520.08	520.08	0.38	31.22	31.22	1.9	58.0	58.0	5.33	67.4	67.4	6.98	8.64	8.64	1.69
-11	388.08	388.08	10.53	168.48	168.48	47.07	104.65	104.65	27.37	274.21	274.21	231.97	638.98	638.98	51.13	538.17	538.17	51.43	4.54	4.54	6.28
-12	428.71	421.38	16.73	335.25	241.15	165.09	130.58	120.19	22.63	198.19	205.92	43.13	212.07	215.97	22.59	168.98	147.47	50.14	2.43	3.0	1.21
-13	421.73	423.08	14.71	183.94	195.44	42.68	437.73	405.31	69.88	414.28	421.76	139.69	610.61	615.38	23.29	289.5	289.23	16.72	3.73	0.19	6.24
-14	373.78	363.33	22.49	142.58	136.41	43.0	448.64	460.06	83.19	598.24	567.5	67.94	234.64	77.56	279.04	158.48	164.12	43.29	1.61	0.08	2.68
-15	369.71	361.32	20.31	147.49	118.97	54.51	306.98	301.48	35.15	122.87	109.52	49.72	115.48	71.4	78.14	148.68	117.17	67.47	1.09	1.42	0.74
-16	419.18	419.08	14.47	284.65	264.01	99.6	107.66	107.35	12.52	479.28	510.36	61.47	134.26	130.48	13.97	198.02	201.21	28.44	1.41	0.58	1.51
-17	472.22	462.0	27.16	267.49	196.73	134.04	485.32	512.67	55.91	591.9	588.96	124.73	284.97	357.2	145.9	346.39	284.33	116.55	0.55	0.12	0.84
-18	391.3	388.6	9.62	151.22	132.42	42.06	468.62	525.67	101.55	200.8	197.56	12.67	150.61	64.27	151.76	251.49	205.87	109.27	4.37	5.28	3.77
-19	954.49	948.66	16.08	990.53	979.64	20.85	494.76	496.89	16.58	627.61	649.92	62.61	526.51	498.02	54.65	525.11	507.34	59.97	0.55	0.48	0.14
-20	420.28	431.49	23.44	220.23	175.21	96.79	128.13	108.33	59.81	528.18	547.09	71.02	636.01	620.52	55.87	359.88	338.83	106.83	2.7	0.53	4.19
-21	611.37	612.66	8.09	969.24	967.97	7.2	141.84	140.47	2.77	223.33	220.24	7.11	223.8	216.74	15.51	183.19	176.15	32.07	14.7	14.78	1.9
-22	666.05	677.97	29.25	452.57	434.17	32.95	377.8	376.69	16.57	226.24	215.63	23.58	212.9	192.78	35.36	277.65	267.15	39.06	2.22	2.36	0.64
-23	546.68	550.94	8.1	989.48	988.58	2.38	361.98	358.59	13.74	472.15	469.96	9.68	381.26	366.78	27.25	438.45	411.62	57.08	1.72	1.77	0.32
-24	683.11	692.69	31.65	446.21	473.52	51.33	394.62	397.71	7.78	202.01	214.78	26.42	192.77	183.47	31.32	148.62	143.66	27.39	2.14	2.2	0.53
-25	727.79	726.15	4.62	1017.52	1017.01	0.89	182.9	182.62	0.89	267.87	264.79	6.49	256.87	250.23	13.27	219.16	217.08	29.48	15.19	13.6	4.22
-26	965.89	969.6	8.54	996.89	998.45	5.47	326.95	329.26	9.33	345.86	338.48	15.18	318.64	315.39	17.52	309.46	324.8	34.46	1.75	1.74	0.13
+1	368.31	368.31	3.72	118.62	118.62	4.11	519.34	519.34	2.77	200.16	200.16	19.18	51.5	51.5	4.07	106.52	106.52	2.0	13.9	13.9	1.15
+2	577.57	579.63	14.26	298.11	287.69	25.04	401.62	403.49	5.56	108.92	119.52	20.26	175.46	148.48	49.99	266.93	204.28	136.79	0.75	0.41	0.59
+3	378.45	377.92	17.49	133.58	120.33	31.7	405.96	363.08	92.9	82.6	79.58	15.37	605.09	598.98	26.19	326.67	262.6	136.73	3.68	0.25	6.11
+4	373.1	369.15	20.1	210.01	216.15	40.09	93.28	91.46	20.61	204.97	195.61	62.67	104.63	103.22	3.66	358.35	299.58	149.23	2.37	1.06	2.9
+5	328.35	329.84	7.36	162.69	153.4	17.04	64.32	66.48	9.1	95.3	100.08	21.11	87.1	75.53	29.03	138.21	111.41	51.91	4.2	5.54	3.46
+6	368.41	369.04	11.26	150.35	148.67	20.18	72.04	69.0	6.23	102.47	96.05	30.23	610.15	608.79	2.45	266.72	240.66	45.65	6.19	3.08	6.59
+7	395.98	405.23	23.06	169.98	178.92	16.38	86.97	94.51	14.15	270.33	281.53	66.6	619.84	620.49	3.64	303.61	275.01	62.14	3.11	2.94	0.95
+8	402.95	402.95	45.04	141.51	141.51	41.7	509.14	509.14	11.8	193.58	193.58	93.02	572.66	572.66	99.37	412.15	412.15	132.02	5.63	5.63	7.93
+9	439.49	431.34	21.29	367.28	354.81	160.26	311.97	356.44	161.34	652.5	767.62	216.65	440.1	474.29	124.44	625.38	645.66	56.62	0.51	0.16	0.67
+10	360.07	360.07	0.95	114.5	114.5	5.18	513.44	513.44	2.91	40.28	40.28	7.32	61.76	61.76	0.71	113.04	113.04	13.46	17.0	17.0	2.65
```

and also the numbers don't match (they are similar). I don't have the domain knowledge to decide whether we can just strip the additional lines and whether there is an element of stochasticity in process that would take us to compare the files by equivalent size or number of lines rather than being exact results.

**Comment by emily101-gif** [comment]
> @emily101-gif I have fixed the galaxy issues of the tool, but the tests are currently not passing because the flowstat3 test files are not equivalent to what the tool is outputting. Currently output1.flowstat3 and output2.flowstat3 files have around 16 more lines than the outputs generated by the tools:
> 
> ```
> JobOutputsError: History item  different than expected, difference (using diff):
> ( /var/folders/23/wwh84vd95rncnf5mx753cpgh0000gp/T/tmp8VmHXbout1.flowstat3 v. /var/folders/23/wwh84vd95rncnf5mx753cpgh0000gp/T/tmpO7Fkyxout1.flowstat3 )
> --- local_file
> +++ history_data
> @@ -1,27 +1,27 @@
>  Population	FSC_mean	FSC_median	FSC_stdev	SSC_mean	SSC_median	SSC_stdev	CD4_mean	CD4_median	CD4_stdev	CCR7_mean	CCR7_median	CCR7_stdev	CD8_mean	CD8_median	CD8_stdev	CCR3_mean	CCR3_median	CCR3_stdev	Percentage_mean	Percentage_median	Percentage_stdev
> -1	362.36	362.36	2.03	115.66	115.66	4.69	520.22	520.22	2.1	187.01	187.01	8.0	49.3	49.3	1.43	71.62	71.62	6.22	9.53	9.53	0.92
> -2	434.28	374.35	111.03	173.06	125.62	92.77	481.01	521.93	74.19	53.87	39.72	27.49	123.6	72.0	94.92	262.34	197.55	140.75	4.77	5.35	4.11
> -3	387.79	395.7	23.62	130.91	119.3	27.93	435.9	410.23	67.59	74.72	69.3	9.68	600.1	585.6	29.27	329.66	275.2	135.27	3.65	0.15	6.14
> -4	362.46	363.32	6.82	204.27	204.11	37.15	89.98	96.34	14.26	176.99	147.5	52.47	99.4	102.85	11.5	379.43	318.19	129.33	2.15	0.42	3.06
> -5	325.38	320.36	10.17	160.67	155.29	19.56	59.04	56.73	12.13	89.3	81.95	21.59	86.04	73.35	29.85	138.09	112.25	52.08	3.85	4.61	3.27
> -6	368.28	368.59	11.22	150.66	148.89	19.84	72.55	69.32	5.76	104.15	96.05	37.15	610.48	612.42	3.86	266.97	244.06	45.55	6.11	3.08	6.26
> -7	396.63	403.26	20.5	168.46	176.59	16.14	87.66	94.51	12.08	279.23	281.53	86.3	621.35	620.71	1.55	304.29	274.19	61.37	3.9	2.99	1.61
> -8	404.55	404.55	47.31	144.35	144.35	45.71	517.41	517.41	0.11	341.18	341.18	115.72	460.13	460.13	258.52	471.42	471.42	48.2	5.63	5.63	7.93
> -9	411.14	431.34	58.13	304.59	331.2	81.01	255.21	292.9	108.35	576.55	562.5	181.39	376.48	302.14	136.76	558.62	616.89	126.67	0.5	0.18	0.68
> -10	355.5	355.5	4.74	112.88	112.88	3.84	520.08	520.08	0.38	31.22	31.22	1.9	58.0	58.0	5.33	67.4	67.4	6.98	8.64	8.64	1.69
> -11	388.08	388.08	10.53	168.48	168.48	47.07	104.65	104.65	27.37	274.21	274.21	231.97	638.98	638.98	51.13	538.17	538.17	51.43	4.54	4.54	6.28
> -12	428.71	421.38	16.73	335.25	241.15	165.09	130.58	120.19	22.63	198.19	205.92	43.13	212.07	215.97	22.59	168.98	147.47	50.14	2.43	3.0	1.21
> -13	421.73	423.08	14.71	183.94	195.44	42.68	437.73	405.31	69.88	414.28	421.76	139.69	610.61	615.38	23.29	289.5	289.23	16.72	3.73	0.19	6.24
> -14	373.78	363.33	22.49	142.58	136.41	43.0	448.64	460.06	83.19	598.24	567.5	67.94	234.64	77.56	279.04	158.48	164.12	43.29	1.61	0.08	2.68
> -15	369.71	361.32	20.31	147.49	118.97	54.51	306.98	301.48	35.15	122.87	109.52	49.72	115.48	71.4	78.14	148.68	117.17	67.47	1.09	1.42	0.74
> -16	419.18	419.08	14.47	284.65	264.01	99.6	107.66	107.35	12.52	479.28	510.36	61.47	134.26	130.48	13.97	198.02	201.21	28.44	1.41	0.58	1.51
> -17	472.22	462.0	27.16	267.49	196.73	134.04	485.32	512.67	55.91	591.9	588.96	124.73	284.97	357.2	145.9	346.39	284.33	116.55	0.55	0.12	0.84
> -18	391.3	388.6	9.62	151.22	132.42	42.06	468.62	525.67	101.55	200.8	197.56	12.67	150.61	64.27	151.76	251.49	205.87	109.27	4.37	5.28	3.77
> -19	954.49	948.66	16.08	990.53	979.64	20.85	494.76	496.89	16.58	627.61	649.92	62.61	526.51	498.02	54.65	525.11	507.34	59.97	0.55	0.48	0.14
> -20	420.28	431.49	23.44	220.23	175.21	96.79	128.13	108.33	59.81	528.18	547.09	71.02	636.01	620.52	55.87	359.88	338.83	106.83	2.7	0.53	4.19
> -21	611.37	612.66	8.09	969.24	967.97	7.2	141.84	140.47	2.77	223.33	220.24	7.11	223.8	216.74	15.51	183.19	176.15	32.07	14.7	14.78	1.9
> -22	666.05	677.97	29.25	452.57	434.17	32.95	377.8	376.69	16.57	226.24	215.63	23.58	212.9	192.78	35.36	277.65	267.15	39.06	2.22	2.36	0.64
> -23	546.68	550.94	8.1	989.48	988.58	2.38	361.98	358.59	13.74	472.15	469.96	9.68	381.26	366.78	27.25	438.45	411.62	57.08	1.72	1.77	0.32
> -24	683.11	692.69	31.65	446.21	473.52	51.33	394.62	397.71	7.78	202.01	214.78	26.42	192.77	183.47	31.32	148.62	143.66	27.39	2.14	2.2	0.53
> -25	727.79	726.15	4.62	1017.52	1017.01	0.89	182.9	182.62	0.89	267.87	264.79	6.49	256.87	250.23	13.27	219.16	217.08	29.48	15.19	13.6	4.22
> -26	965.89	969.6	8.54	996.89	998.45	5.47	326.95	329.26	9.33	345.86	338.48	15.18	318.64	315.39	17.52	309.46	324.8	34.46	1.75	1.74	0.13
> +1	368.31	368.31	3.72	118.62	118.62	4.11	519.34	519.34	2.77	200.16	200.16	19.18	51.5	51.5	4.07	106.52	106.52	2.0	13.9	13.9	1.15
> +2	577.57	579.63	14.26	298.11	287.69	25.04	401.62	403.49	5.56	108.92	119.52	20.26	175.46	148.48	49.99	266.93	204.28	136.79	0.75	0.41	0.59
> +3	378.45	377.92	17.49	133.58	120.33	31.7	405.96	363.08	92.9	82.6	79.58	15.37	605.09	598.98	26.19	326.67	262.6	136.73	3.68	0.25	6.11
> +4	373.1	369.15	20.1	210.01	216.15	40.09	93.28	91.46	20.61	204.97	195.61	62.67	104.63	103.22	3.66	358.35	299.58	149.23	2.37	1.06	2.9
> +5	328.35	329.84	7.36	162.69	153.4	17.04	64.32	66.48	9.1	95.3	100.08	21.11	87.1	75.53	29.03	138.21	111.41	51.91	4.2	5.54	3.46
> +6	368.41	369.04	11.26	150.35	148.67	20.18	72.04	69.0	6.23	102.47	96.05	30.23	610.15	608.79	2.45	266.72	240.66	45.65	6.19	3.08	6.59
> +7	395.98	405.23	23.06	169.98	178.92	16.38	86.97	94.51	14.15	270.33	281.53	66.6	619.84	620.49	3.64	303.61	275.01	62.14	3.11	2.94	0.95
> +8	402.95	402.95	45.04	141.51	141.51	41.7	509.14	509.14	11.8	193.58	193.58	93.02	572.66	572.66	99.37	412.15	412.15	132.02	5.63	5.63	7.93
> +9	439.49	431.34	21.29	367.28	354.81	160.26	311.97	356.44	161.34	652.5	767.62	216.65	440.1	474.29	124.44	625.38	645.66	56.62	0.51	0.16	0.67
> +10	360.07	360.07	0.95	114.5	114.5	5.18	513.44	513.44	2.91	40.28	40.28	7.32	61.76	61.76	0.71	113.04	113.04	13.46	17.0	17.0	2.65
> ```
> 
> and also the numbers don't match (they are similar). I don't have the domain knowledge to decide whether we can just strip the additional lines and whether there is an element of stochasticity in process that would take us to compare the files by equivalent size or number of lines rather than being exact results.



@pcm32  Strangely when I do the first test run in planemo - the flowsom mapping tool produces the same output as in the test file. The values appear to be exactly the same and have the same number of lines. It's really strange that yours is showing negative populations (and even more negative populations than there are positive). There is also no stochasticity in this tool. It is just summarising the results of FlowSOM and adding the results to the same FCS files used for the flowSOM. 



planemo output:::::
Population	FSC_mean	FSC_median	FSC_stdev	SSC_mean	SSC_median	SSC_stdev	CD4_mean	CD4_median	CD4_stdev	CCR3_mean	CCR3_median	CCR3_stdev	CD8_mean	CD8_median	CD8_stdev	CCR7_mean	CCR7_median	CCR7_stdev	Percentage_mean	Percentage_median	Percentage_stdev
1	449.517033333333	417.6756	80.0730653843309	459.103833333333	390.0447	216.073684871165	39.8154533333333	40.13677	5.01452185878507	150.838	150.4859	38.395660843512	250.793593333333	284.0427	67.111722169429	167.260033333333	164.4792	32.347821647266	7.02	7.275	5.25714038237519
2	399.186966666667	394.1149	10.9973232744761	238.146333333333	249.3538	37.7163583478487	63.80977	55.70256	19.0417661339252	184.419233333333	158.2486	77.9796674462217	491.019236666667	521.78231	57.0066099143251	401.375833333333	357.4974	109.343631419042	7.67666666666667	2.205	10.5603389307983
3	467.2606	467.2606	62.422538115011	229.3288	229.3288	7.17175981750645	180.70303	180.70303	62.3625330335595	531.77725	531.77725	128.442764822021	687.00605	687.00605	95.8751235368435	776.07575	776.07575	7.17819448921528	0.1775	0.1775	0.215667568261897
4	491.897133333333	409.0643	149.780851176121	278.052733333333	184.868	168.832454839268	448.970486666667	476.89881	53.4724893652207	158.223133333333	167.6959	37.8623778168162	113.65597	71.6557	73.6871838168124	165.000733333333	136.2907	69.3533555861815	28.3566666666667	37.7	22.1368343114668
5	516.3916	490.4522	70.6730826772824	564.707533333333	496.6552	221.791228156961	217.89667	148.68824	136.239830947248	155.259766666667	151.626	26.5492160965881	386.466533333333	400.36621	119.854921059911	258.248033333333	210.7229	118.202621439304	20.925	21.04	10.7479614346163
6	503.986666666667	544.9372	91.1725446226732	529.892566666667	588.058	286.9690970419	66.6792266666667	68.47826	17.2981163164355	379.999266666667	363.4541	61.4031448561337	359.096546666667	354.7923	138.223751503987	222.893833333333	240.6476	33.605210605847	3.45666666666667	1.035	4.51866776089295
7	543.537233333333	560.5087	42.3007222355994	656.858366666667	727.4167	153.183832006003	162.490643333333	120.46087	73.4431415786262	337.339266666667	313.5	69.0314434588567	117.343473333333	128.84783	25.6863284384793	154.5796	152.2522	13.606813291877	1.55333333333333	1.15	1.49633997919368
8	637.9505	629.9274	49.7939072153411	803.6457	786.0875	145.730875121197	254.312376666667	225.76559	58.7006535935217	325.855566666667	335.3947	23.430565280704	338.334176666667	319.91354	68.775726534905	252.833433333333	239.1529	43.9294104988143	29.25	27.815	11.9174735158086
9	713.288166666667	727.5	183.065256728641	653.217366666667	731	248.41473494695	462.796183333333	530.46667	211.3275442529	834.4092	870.5	72.4875762589011	714.039573333333	614.71875	210.964602501457	670.178633333333	604.3667	275.704133227076	0.273333333333333	0.15	0.32316146634977
10	470.2887	463.1167	45.1998847698753	375.647433333333	305.7	202.644669803485	169.1044	132.08403	67.2489033808351	592.7282	610.3137	35.3658586669404	284.34763	252.89583	110.968356521537	255.033566666667	243.4132	29.0586790013471	1.37	0.3	1.90549206243427



Test-data output::::
Population	FSC_mean	FSC_median	FSC_stdev	SSC_mean	SSC_median	SSC_stdev	CD4_mean	CD4_median	CD4_stdev	CCR3_mean	CCR3_median	CCR3_stdev	CD8_mean	CD8_median	CD8_stdev	CCR7_mean	CCR7_median	CCR7_stdev	Percentage_mean	Percentage_median	Percentage_stdev
1	449.517033333333	417.6756	80.0730653843309	459.103833333333	390.0447	216.073684871165	39.8154533333333	40.13677	5.01452185878507	150.838	150.4859	38.395660843512	250.793593333333	284.0427	67.111722169429	167.260033333333	164.4792	32.347821647266	7.02	7.275	5.25714038237519
2	399.186966666667	394.1149	10.9973232744761	238.146333333333	249.3538	37.7163583478487	63.80977	55.70256	19.0417661339252	184.419233333333	158.2486	77.9796674462217	491.019236666667	521.78231	57.0066099143251	401.375833333333	357.4974	109.343631419042	7.67666666666667	2.205	10.5603389307983
3	467.2606	467.2606	62.422538115011	229.3288	229.3288	7.17175981750645	180.70303	180.70303	62.3625330335595	531.77725	531.77725	128.442764822021	687.00605	687.00605	95.8751235368435	776.07575	776.07575	7.17819448921528	0.1775	0.1775	0.215667568261897
4	491.897133333333	409.0643	149.780851176121	278.052733333333	184.868	168.832454839268	448.970486666667	476.89881	53.4724893652207	158.223133333333	167.6959	37.8623778168162	113.65597	71.6557	73.6871838168124	165.000733333333	136.2907	69.3533555861815	28.3566666666667	37.7	22.1368343114668
5	516.3916	490.4522	70.6730826772824	564.707533333333	496.6552	221.791228156961	217.89667	148.68824	136.239830947248	155.259766666667	151.626	26.5492160965881	386.466533333333	400.36621	119.854921059911	258.248033333333	210.7229	118.202621439304	20.925	21.04	10.7479614346163
6	503.986666666667	544.9372	91.1725446226732	529.892566666667	588.058	286.9690970419	66.6792266666667	68.47826	17.2981163164355	379.999266666667	363.4541	61.4031448561337	359.096546666667	354.7923	138.223751503987	222.893833333333	240.6476	33.605210605847	3.45666666666667	1.035	4.51866776089295
7	543.537233333333	560.5087	42.3007222355994	656.858366666667	727.4167	153.183832006003	162.490643333333	120.46087	73.4431415786262	337.339266666667	313.5	69.0314434588567	117.343473333333	128.84783	25.6863284384793	154.5796	152.2522	13.606813291877	1.55333333333333	1.15	1.49633997919368
8	637.9505	629.9274	49.7939072153411	803.6457	786.0875	145.730875121197	254.312376666667	225.76559	58.7006535935217	325.855566666667	335.3947	23.430565280704	338.334176666667	319.91354	68.775726534905	252.833433333333	239.1529	43.9294104988143	29.25	27.815	11.9174735158086
9	713.288166666667	727.5	183.065256728641	653.217366666667	731	248.41473494695	462.796183333333	530.46667	211.3275442529	834.4092	870.5	72.4875762589011	714.039573333333	614.71875	210.964602501457	670.178633333333	604.3667	275.704133227076	0.273333333333333	0.15	0.32316146634977
10	470.2887	463.1167	45.1998847698753	375.647433333333	305.7	202.644669803485	169.1044	132.08403	67.2489033808351	592.7282	610.3137	35.3658586669404	284.34763	252.89583	110.968356521537	255.033566666667	243.4132	29.0586790013471	1.37	0.3	1.90549206243427

**Comment by pcm32** [comment]
@emily101-gif the initial line with a - or + is the diff showing you the two different files. The second set of lines (pluses) is the result of the test run, the minuses is the content of the file given in the test data directory (test-data/run1 and run2). So the files there don't match either what you got as result.

**Comment by emily101-gif** [comment]
> @emily101-gif the initial line with a - or + is the diff showing you the two different files. The second set of lines (pluses) is the result of the test run, the minuses is the content of the file given in the test data directory (test-data/run1 and run2). So the files there don't match either what you got as result.

OK well if you're happy with me doing so then I can change the output files to the ones we are getting - as the tool seems to be working. It could be that there were some errors with the test files which were never checked as it was not pushed to the toolshed?

**Comment by pcm32** [comment]
Yes, if you are satisfied with what the tool does, then let's change the expected results file.

**Comment by emily101-gif** [comment]
> Yes, if you are satisfied with what the tool does, then let's change the expected results file.

Great I will change it now.

**Comment by emily101-gif** [comment]
Hi Pablo. I've just noticed that the tool on this branch doesn't appear to be updated to the same point as the master. The tool repository on this branch doesn't contain the R code and therefore the XML file doesn't link to the script within the tool repo. Just wondering if this was deliberate? @pcm32

**Comment by pcm32** [comment]
@emily101-gif to which R code do you refer? If you look at the changes of the PR, there is no R code deletion as far as I can see. The python code doesn't call any R code either, besides `cent_adjust` (not sure if this is R), which is provided by the flock dependency AFAIK. Maybe if you paste links to the R code that you mean? What particular differences do you see with master? Again, they would be reflected in the PR changes here. Or do you mean a different git repository, such as immport-galaxy main repo?

**Comment by emily101-gif** [comment]
Really sorry I think I was looking at the wrong tool (on my previous comment about missing R script)! 

I'm still getting the same outputs for the flowstat3 files for both runs though and I get no output when I run diff on the two files. I have attached them below as txt files so they could be loaded into Github for you to see. Therefore, I don't think there is much point me changing the flowstat3 example output files as they would be the same as the ones I'm getting. The only other I can think is that it could be due to the order of the output files in the  <test> tag: flowstat3 comes before flowstat2 - but they are named and I would ealso xpect an error to also be occurring with flowstat2 ... @pcm32 

run1:

flowstat3 expected output: [out1.txt](https://github.com/AstraZeneca-Omics/immport-galaxy-tools/files/4965441/out1.txt)

flowstat3 output from running in planemo 
[Galaxy13-[mfi_descriptive_stats_of_CrossSample_on_list_using_mfi].txt](https://github.com/AstraZeneca-Omics/immport-galaxy-tools/files/4965444/Galaxy13-.mfi_descriptive_stats_of_CrossSample_on_list_using_mfi.txt)

run2:

flowstat3 expected output: [out2.txt](https://github.com/AstraZeneca-Omics/immport-galaxy-tools/files/4965942/out2.txt)

flowstats3 outcome from running in planemo:
[Galaxy44-[gmfi_descriptive_stats_of_CrossSample_on_list_using_gmfi].txt](https://github.com/AstraZeneca-Omics/immport-galaxy-tools/files/4965944/Galaxy44-.gmfi_descriptive_stats_of_CrossSample_on_list_using_gmfi.txt)

**Comment by pcm32** [comment]
Tests are passing, maybe my local branch was dirty somehow.

**Review by pcm32 — APPROVED** [review]

**Pull request merged**
